# Generated by Django 3.0.9 on 2020-08-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forager.Plant')),
            ],
        ),
    ]
