# Generated by Django 3.0.9 on 2020-08-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forager', '0003_auto_20200811_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plants',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='UserPlants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forager.Plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forager.User')),
            ],
        ),
    ]
