# Generated by Django 3.0.9 on 2020-08-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forager', '0004_auto_20200811_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plants',
            field=models.ManyToManyField(related_name='plants', to='forager.Plant'),
        ),
    ]
