# Generated by Django 3.0.9 on 2020-08-19 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forager', '0007_auto_20200818_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2020, 8, 19, 16, 35, 8, 163571, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
